variant: fcos
version: 1.4.0
passwd:
  users:
  - name: root
    ssh_authorized_keys:
    - "<ENTER_AUTHORIZED_PODMAN_KEY>"
  - name: <ENTER_USERNAME_HERE>
    ssh_authorized_keys:
    - "<ENTER_AUTHORIZED_USER_KEY>"
    - "<ENTER_AUTHORIZED_PODMAN_KEY>"
    groups:
    - wheel
    - sudo
storage:
  files:
    - path: /etc/fuse.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          user_allow_other
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: fedora-coreos-podman
systemd:
  units:
  - name: mkdir-Users-<ENTER_USERNAME_HERE>.service
    enabled: true
    contents: |
      [Unit]
      Description=Enable mount points in / for ostree
      DefaultDependencies=no
      ConditionPathExists=!/Users/<ENTER_USERNAME_HERE>

      [Service]
      Type=oneshot
      ExecStartPre=chattr -i /
      ExecStart=mkdir -p '/Users/<ENTER_USERNAME_HERE>'
      ExecStart=chown -R <ENTER_USERNAME_HERE>:<ENTER_USERNAME_HERE> '/Users/<ENTER_USERNAME_HERE>'
      ExecStopPost=chattr +i /

      [Install]
      WantedBy=local-fs.target
  - name: var-mnt-lima\x2dcidata.mount
    enabled: true
    contents: |
      [Unit]
      Description=CoreOS Dynamic Mount for /var/mount/lima-cidata
      Before=local-fs.target
      After=var.mount

      [Mount]
      What=/dev/disk/by-label/cidata
      Where=/var/mnt/lima-cidata
      Type=none

      [Install]
      WantedBy=remote-fs.target
      RequiredBy=fcos-lima-workaround-ssh-ready.service
  - name: fcos-lima-workaround-ssh-ready.service
    enabled: true
    contents: |
      [Unit]
      Description=CoreOS workaround for lima requirment #2
      After=var-mnt-lima\x2dcidata.mount

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/bin/bash -c "cp /var/mnt/lima-cidata/meta-data /run/lima-ssh-ready"

      [Install]
      WantedBy=create-lima-guestagent-systemd-unit.service
  - name: create-lima-guestagent-systemd-unit.service
    enabled: true
    contents: |
      [Unit]
      Description=CoreOS workaround for lima-guestagent
      After=fcos-lima-workaround-ssh-ready.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/bin/bash -c "cp /var/mnt/lima-cidata/lima-guestagent /usr/local/bin/"
      ExecStart=/bin/bash -c "chmod +x /usr/local/bin/lima-guestagent"
      ExecStart=/bin/bash -c "lima-guestagent install-systemd"

      [Install]
      WantedBy=fcos-lima-workaround-boot-done.service
  - name: fcos-lima-workaround-boot-done.service
    enabled: true
    contents: |
      [Unit]
      Description=CoreOS workaround for lima requirment #3
      After=create-lima-guestagent-systemd-unit.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/bin/bash -c "cp /var/mnt/lima-cidata/meta-data /run/lima-boot-done"

      [Install]
      WantedBy=multi-user.target
  - name: podman.service
    enabled: true
  - name: docker.service
    enabled: false
